kind: pipeline
type: docker
name: webUITest

platform:
  os: linux
  arch: amd64

steps:
  - name: planka
    image: node/12.22-alpine3.14
    environment:
      DATABASE_URL: postgresql://postgres@postgres/planka
      DRONE: true
      LAUNCH_URL: 'http://planka:3000'
    commands:
      - npm i
      - npm run server:db:init
      - npm start &
      - until curl -s http://planka:3000; do sleep 5; done
      - until curl -s http://planka:1337; do sleep 5; done
      - cd client
      - npm run test:webui tests/acceptance/features

services:
  - name: postgres
    image: postgres
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust

  - name: selenium
    image: selenium/standalone-chrome-debug

trigger:
  branch:
    - master
