kind: pipeline
type: docker
name: webUITest

platform:
  os: linux
  arch: amd64

steps:
  - name: planka
    image: node
    detach: true
    environment:
      DATABASE_URL: postgresql://postgres@postgres/planka
    commands:
      - npm i
      - npm run server:db:init
      - npm start

  - name: wait-for-server
    image: 'owncloudci/wait-for:latest'
    commands:
      - wait-for -it planka:3000 -t 600
      - wait-for -it planka:1337 -t 600

  - name: ui-tests
    image: node
    environment:
      CI: true
      LAUNCH_URL: 'http://planka:3000'
    commands:
      - cd client
      - npm i
      - npm run test:webui tests/acceptance/features

services:
  - name: selenium
    image: selenium/standalone-chrome-debug

  - name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: planka
      POSTGRES_HOST_AUTH_METHOD: trust

trigger:
  branch:
    - master
