language: node_js

services:
  - postgresql
  - docker
  - xvfb

env:
  global:
    - POSTGRES_DB=planka
    - POSTGRES_HOST_AUTH_METHOD=trust
    - DRONE=false

before_install:
  - psql -c 'CREATE DATABASE planka;' -U postgres
  - docker run -d -p 4444:4444 -p 5900:5900 --net=host -v /dev/shm:/dev/shm selenium/standalone-chrome-debug
  - nvm install v12
  - nvm use v12

install:
  - npm i

before_script:
  - npm run server:db:init
  - npm start &
  - until curl -s http://localhost:3000; do sleep 5; done
  - until curl -s http://localhost:1337; do sleep 5; done

script:
  - cd client
  - npm run test:webui tests/acceptance/features

branches:
  only:
    - master
