language: node_js

sudo: true

services:
  - mongodb
  - docker
  - xvfb

env:
  global:
    - POSTGRES_DB=planka
    - POSTGRES_HOST_AUTH_METHOD=trust

before_install:
  - docker run -d -p 4444:4444 -p 5900:5900 --net=host -v /dev/shm:/dev/shm selenium/standalone-chrome-debug
  - nvm install v13.9.0
  - nvm use v13.9.0

install:
  - npm ci

before_script:
  - npm run server:db:init
  - npm start
  - until curl -s http://localhost:3000; do sleep 5; done
  - until curl -s http://localhost:1337; do sleep 5; done

script:
  - cd $TRAVIS_BUILD_DIR/client/
  - npm run test:webui tests/acceptance/features
